services:
  mysql-blog:
    image: mysql:8
    container_name: mysql-blog
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD: root
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack-local
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: always